export default {
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGGEDOUT: 'USER_LOGGEDOUT',
  USER_SIGNEDUP: 'USER_SIGNEDUP',
  SIGNINGUP_FAILED: 'SIGNINGUP_FAILED',
};

export const formActionTypes = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  RESET_PASSWORD: 'RESET_PASSWORD',
};
