export const userActionTypes = {
  TOKEN_VERIFIED: 'TOKEN_VERIFIED',
  VERIFY_TOKEN_FAILED: 'VERIFY_TOKEN_FAILED',
  LOGGEDIN: 'LOGGEDIN',
  LOGGEDOUT: 'LOGGEDOUT',
  SIGNEDUP: 'SIGNEDUP',
  BOARD_ADDED: 'BOARD_ADDED',
  EMAIL_CONFIRMED: 'EMAIL_CONFIRMED',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
  LOGGEDOUT_FAILED: 'LOGGEDOUT_FAILED',
  SIGNINGUP_FAILED: 'SIGNINGUP_FAILED',
  LOGGING_FAILED: 'LOGGING_FAILED',
  EMAIL_CONFIRMATION_FAILED: 'EMAIL_CONFIRMATION_FAILED',
  ALL_BOARDS_DOWNLOADED: 'ALL_BOARDS_DOWNLOADED',
  ALL_BOARDS_DOWNLOADING_FAILED: 'ALL_BOARDS_DOWNLOADING_FAILED',
};

export const boardActionTypes = {
  CREATED: 'CREATED',
  CREATE_FAILED: 'CREATE_FAILED',
  BOARD_DOWNLOADED: 'BOARD_DOWNLOADED',
  BOARD_DOWNLOAD_FAILED: 'BOARD_DOWNLOAD_FAILED',
};

export const formActionTypes = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};
